#
# Waylandify Configuration File
#
# Add the programs you want to modify under the [programs] section.
# Each program needs a unique key (e.g., [programs.vscode]).
#
# - 'names': A list of possible binary names for the program.
#            The script will use `which` to find the first valid one.
# - 'flags': A list of command-line flags to apply to the .desktop files.
#

[programs.vscode]
names = ["code"]
flags = [
  "--enable-features=UseOzonePlatform",
  "--ozone-platform=wayland",
  "--enable-features=TouchpadOverscrollHistoryNavigation",
]

[programs.brave]
names = ["brave-browser", "brave-browser-stable"]
flags = [
  "--enable-features=TouchpadOverscrollHistoryNavigation",
]

[programs.edge]
names = ["microsoft-edge-stable", "microsoft-edge"]
flags = [
  "--enable-features=TouchpadOverscrollHistoryNavigation",
]
